apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-root
  namespace: cert-manager
spec:
  isCA: true
  commonName: my-ca
  secretName: ca-root-secret
  dnsNames:
    - ${ROOT_DOMAIN}
  issuerRef:
    name: selfsigned-ca
    kind: ClusterIssuer
    group: cert-manager.io
