apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: airbyte-tls
  namespace: airbyte
spec:
  secretName: airbyte-tls
  dnsNames:
  - $AIRBYTE_HOST
  issuerRef:
    name: local-issuer
    kind: ClusterIssuer
    group: cert-manager.io
