apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-tls
  namespace: authentik
spec:
  secretName: authentik-tls
  dnsNames:
    - $AUTHENTIK_HOST
  issuerRef:
    name: local-issuer
    kind: ClusterIssuer
    group: cert-manager.io
