apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik-web
  namespace: authentik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`$AUTHENTIK_HOST`)
      kind: Rule
      services:
        - name: authentik-server
          port: 80
  tls:
    secretName: authentik-tls
