apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: authentik-tls
  namespace: authentik
spec:
  secretName: authentik-tls
  issuerRef:
    name: local-issuer
    kind: ClusterIssuer
  commonName: ${authentik_hostname}
  dnsNames:
    - ${authentik_hostname}
